apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-ingest-http.fullname" . }}-config
  labels:
    {{- include "wasp-ingest-http.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  kafkaLogLevel: {{ .Values.config.kafka.logLevel }}
  kafkaBrokers: {{ include "wasp-ingest-http.kafka.brokers" . }}
  kafkaPayloadTopic: {{ .Values.config.kafka.rawPayloadTopic }}
  waspIngestName: {{ .Values.config.waspIngestName }}
  ingestIdJsonPath: {{ .Values.config.ingestIdJsonPath }}
