{{- $fullName := include "wasp-ingest-http.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wasp-ingest-http.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ $fullName }}
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: {{ .Values.config.port }}
